# Bab 8. NumPy: Array, Broadcasting, dan Vektorisasi

Kode pendamping buku *Python untuk Machine Learning dan Data
Science*. Jalankan selnya berurutan dari atas, sebab sebagian
sel memakai peubah dari sel sebelumnya.

Notebook ini dibangkitkan dari naskah buku. Jangan disunting di
sini, sunting listing pada berkas `.tex` lalu bangkitkan ulang.

## 1. Membandingkan waktu eksekusi

In [ ]:
import numpy as np, math, timeit

setup = """
import numpy as np, math
lst = [i*0.001 for i in range(1_000_000)]
arr = np.array(lst)
"""

def waktu(perintah, ulang=5):
    t = timeit.repeat(perintah, setup=setup,
                      repeat=ulang, number=1)
    return min(t) * 1000   # milidetik

print(waktu("[math.sqrt(x) for x in lst]"))
print(waktu("np.sqrt(arr)"))

Keluaran yang diharapkan:

```
44.4
2.3
```

## 2. Metadata sebuah array

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.shape)      # ukuran tiap dimensi
print(A.ndim)       # banyak dimensi
print(A.size)       # total elemen
print(A.dtype)      # tipe elemen
print(A.itemsize)   # byte per elemen
print(A.nbytes)     # total byte buffer
print(A.strides)    # lompatan byte per dimensi

Keluaran yang diharapkan:

```
(2, 3)
2
6
int64
8
48
(24, 8)
```

## 3. arange versus linspace

In [ ]:
import numpy as np

print(np.linspace(0, 1, 5))
print(np.arange(0, 1, 0.25))

Keluaran yang diharapkan:

```
[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75]
```

## 4. Generator acak yang reproducible

In [ ]:
rng = np.random.default_rng(seed=42)
X = rng.normal(loc=0.0, scale=1.0, size=(3, 2))

## 5. View berbagi memori

In [ ]:
a = np.arange(6)
b = a[1:4]        # view, bukan salinan
b[0] = 99
print(a)

c = a[1:4].copy() # salinan mandiri
c[0] = -1
print(a)

Keluaran yang diharapkan:

```
[ 0 99  2  3  4  5]
[ 0 99  2  3  4  5]
```

## 6. Pengindeksan fancy dan boolean

In [ ]:
m = np.arange(12).reshape(3, 4)

print(m[[0, 2], [1, 3]])   # elemen (0,1) dan (2,3)
print(m[m % 2 == 0])       # semua elemen genap

Keluaran yang diharapkan:

```
[ 1 11]
[ 0  2  4  6  8 10]
```

## 7. Broadcasting membentuk tabel

In [ ]:
u = np.array([[1], [2], [3]])      # bentuk (3, 1)
v = np.array([[10, 20, 30, 40]])   # bentuk (1, 4)

print((u + v).shape)
print(u + v)

Keluaran yang diharapkan:

```
(3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
```

## 8. Sigmoid tervektorisasi

In [ ]:
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

z = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
print(np.round(sigmoid(z), 4))

Keluaran yang diharapkan:

```
[0.1192 0.2689 0.5    0.7311 0.8808]
```

## 9. Pengaruh argumen axis

In [ ]:
X = np.array([[2., 4., 6.],
              [1., 3., 5.],
              [7., 9., 11.]])

print(X.sum())          # seluruh elemen
print(X.sum(axis=0))    # meringkas baris
print(X.sum(axis=1))    # meringkas kolom

Keluaran yang diharapkan:

```
48.0
[10. 16. 22.]
[12.  9. 27.]
```

## 10. Menyelesaikan sistem linear

In [ ]:
M = np.array([[2., 1.],
              [1., 3.]])
b = np.array([5., 10.])

x = np.linalg.solve(M, b)
print(x)
print(M @ x)     # verifikasi

Keluaran yang diharapkan:

```
[1. 3.]
[ 5. 10.]
```

## 11. Standardisasi dengan
broadcasting

In [ ]:
D = np.array([[170., 65.],
              [180., 80.],
              [160., 55.],
              [175., 72.],
              [165., 60.]])

mu = D.mean(axis=0)      # bentuk (2,)
sd = D.std(axis=0)       # bentuk (2,)
Z = (D - mu) / sd        # broadcasting (5,2) - (2,)

print(np.round(mu, 4))
print(np.round(sd, 4))
print(np.round(Z, 4))

Keluaran yang diharapkan:

```
[170.    66.4]
[ 7.0711  8.8227]
[[ 0.     -0.1587]
 [ 1.4142  1.5415]
 [-1.4142 -1.2921]
 [ 0.7071  0.6347]
 [-0.7071 -0.7254]]
```

## 12. Memeriksa hasil standardisasi

In [ ]:
print(np.round(Z.mean(axis=0), 10))
print(np.round(Z.std(axis=0), 10))

Keluaran yang diharapkan:

```
[ 0. -0.]
[1. 1.]
```